--1
CREATE TABLE TB_CLIENTE(
	MATRICULA INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(40),
	TELEFONE VARCHAR(10));

SELECT * FROM TB_CLIENTE

--2
CREATE OR ALTER PROCEDURE SP_INCLUI_CLIENTE(@MATRICULA INT,
											@NOME VARCHAR(40),
											@TELEFONE VARCHAR(10))
AS
BEGIN
	INSERT INTO TB_CLIENTE (MATRICULA, NOME, TELEFONE)
	VALUES (@MATRICULA, @NOME, @TELEFONE)
END

EXEC SP_INCLUI_CLIENTE 1, 'Etelvino', '1234567890';

--3
CREATE PROCEDURE SP_ALTERA_CLIENTE (@MATRICULA INT, @NOME VARCHAR(40), @TELEFONE VARCHAR(10))
AS
	UPDATE TB_CLIENTE SET NOME = @NOME, TELEFONE = @TELEFONE WHERE MATRICULA = @MATRICULA;

EXEC SP_ALTERA_CLIENTE 1, 'ETELVINO MENDONÇA', '79981650084'

--4
CREATE PROCEDURE SP_REMOVE_CLIENTE (@MATRICULA INT, @RESULTADO INT OUTPUT)
AS
	DELETE FROM TB_CLIENTE WHERE MATRICULA = @MATRICULA;
	SET @RESULTADO = @@ROWCOUNT;

DECLARE @RESULT INT;
EXEC SP_REMOVE_CLIENTE 1, @RESULT OUTPUT;
PRINT @RESULT

--5
ALTER PROCEDURE SP_ALTERA_CLIENTE (@MATRICULA INT, @NOME VARCHAR(40), @TELEFONE VARCHAR(10))
AS
	UPDATE TB_CLIENTE
	SET NOME = ISNULL(@NOME, NOME),
		TELEFONE = ISNULL(@TELEFONE, TELEFONE)
	WHERE MATRICULA = @MATRICULA;

EXEC SP_ALTERA_CLIENTE 1, 'MENDONÇÃO', NUll