--1
CREATE TABLE TB_FUNCIONARIO
(
	MATRICULA INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(40) NOT NULL,
	TELEFONE VARCHAR(20),
	ENDERECO VARCHAR(40),
	SALARIO DECIMAL(10,2),
	PENDENCIA VARCHAR(40)
)

SELECT * FROM TB_FUNCIONARIO

--2
CREATE PROCEDURE SP_ATUALIZA_PENDENCIA
AS
BEGIN
    DECLARE @MATRICULA INT,
            @NOME VARCHAR(40),
            @TELEFONE VARCHAR(20),
            @ENDERECO VARCHAR(40),
            @SALARIO DECIMAL(10,2),
            @PENDENCIA VARCHAR(40)

    -- DECLARA O CURSOR
    DECLARE CURSOR_FUNCIONARIO CURSOR FOR
    SELECT MATRICULA, NOME, TELEFONE, ENDERECO, SALARIO
    FROM TB_FUNCIONARIO

    -- ABRE O CURSOR
    OPEN CURSOR_FUNCIONARIO

    -- LÊ A PRIMEIRA LINHA DO CURSOR
    FETCH NEXT FROM CURSOR_FUNCIONARIO INTO @MATRICULA, @NOME, @TELEFONE, @ENDERECO, @SALARIO

    -- LOOP ATRAVÉS DAS LINHAS DO CURSOR
    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- VERIFICA SE TODOS OS CAMPOS TÊM VALORES
        IF @NOME IS NOT NULL AND @TELEFONE IS NOT NULL AND @ENDERECO IS NOT NULL AND @SALARIO IS NOT NULL
        BEGIN
            SET @PENDENCIA = 'SEM PENDÊNCIA'
        END
        ELSE
        BEGIN
            SET @PENDENCIA = 'EXISTE PENDÊNCIA'
        END

        -- ATUALIZA A TABELA TB_FUNCIONARIO COM O VALOR DE PENDENCIA
        UPDATE TB_FUNCIONARIO
        SET PENDENCIA = @PENDENCIA
        WHERE MATRICULA = @MATRICULA

        -- LÊ A PRÓXIMA LINHA DO CURSOR
        FETCH NEXT FROM CURSOR_FUNCIONARIO INTO @MATRICULA, @NOME, @TELEFONE, @ENDERECO, @SALARIO
    END

    -- FECHA E DESALOCA O CURSOR
    CLOSE CURSOR_FUNCIONARIO
    DEALLOCATE CURSOR_FUNCIONARIO
END
