--1
CREATE PROCEDURE 
	SP_AUMENTA_SALARIO (@ANOADMISSAO INT,
						@SALARIOATUAL DECIMAL(10,2),
						@SALARIOAUMENTADO DECIMAL(10,2) OUTPUT)
AS
BEGIN
	DECLARE @PERCENTUALAUMENTO DECIMAL(5,2)

	IF @ANOADMISSAO < 2010
	BEGIN
		SET @PERCENTUALAUMENTO = 0.30 --30%
	END
	ELSE IF @ANOADMISSAO >= 2010 AND @ANOADMISSAO <= 2015
	BEGIN
		SET @PERCENTUALAUMENTO = 0.20 --20%
	END
	ELSE
	BEGIN
		SET @PERCENTUALAUMENTO = 0.10 --10%
	END

	--AQUI CALCULA O SALÁRIO NOVO
	SET @SALARIOAUMENTADO = ((@SALARIOATUAL * @PERCENTUALAUMENTO) + @SALARIOATUAL)
END

--COMO TESTAR
--PRIMEIRO DECLARA A VARIÁVEL QUE IRÁ RECEBER O VALOR
DECLARE @SALARIOAUMENTADO DECIMAL(10,2)

--EXECUTA A CHAMADA DA PROCEDURE INFORMANDO OS PARÂMETROS DE ENTRADA
EXEC SP_AUMENTA_SALARIO
	@ANOADMISSAO = 2018,
	@SALARIOATUAL = 1000,
	@SALARIOAUMENTADO = @SALARIOAUMENTADO OUTPUT

--EXIBE O RESULTADO
SELECT @SALARIOAUMENTADO AS NOVOSALARIO

--2
CREATE TABLE
	TB_FUNCIONARIO (MATRICULA INT NOT NULL PRIMARY KEY,
					NM_FUNCIONARIO VARCHAR(40) NOT NULL,
					ANO_ADMISSAO INT NOT NULL,
					SALARIO DECIMAL(10,2) NOT NULL)

--3
CREATE PROCEDURE SP_ATUALIZA_SALARIO_FUNCIONARIOS
AS
BEGIN
    DECLARE @MATRICULA INT,
            @NM_FUNCIONARIO VARCHAR(40),
            @ANO_ADMISSAO INT,
            @SALARIO DECIMAL(10,2),
            @NOVO_SALARIO DECIMAL(10,2)

    -- Declara o cursor
    DECLARE CURSOR_FUNCIONARIOS CURSOR FOR
    SELECT MATRICULA, NM_FUNCIONARIO, ANO_ADMISSAO, SALARIO
    FROM TB_FUNCIONARIO

    -- Abre o cursor
    OPEN CURSOR_FUNCIONARIOS

    -- Lê a primeira linha do cursor
    FETCH NEXT FROM CURSOR_FUNCIONARIOS INTO @MATRICULA, @NM_FUNCIONARIO, @ANO_ADMISSAO, @SALARIO

    -- Loop através das linhas do cursor
    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- Chama o procedimento para calcular o novo salário
        EXEC SP_AUMENTA_SALARIO 
            @ANOADMISSAO = @ANO_ADMISSAO,
            @SALARIOATUAL = @SALARIO,
            @SALARIOAUMENTADO = @NOVO_SALARIO OUTPUT

        -- Atualiza a tabela TB_FUNCIONARIO com o novo salário
        UPDATE TB_FUNCIONARIO
        SET SALARIO = @NOVO_SALARIO
        WHERE MATRICULA = @MATRICULA

        -- Lê a próxima linha do cursor
        FETCH NEXT FROM CURSOR_FUNCIONARIOS INTO @MATRICULA, @NM_FUNCIONARIO, @ANO_ADMISSAO, @SALARIO
    END

    -- Fecha e desaloca o cursor
    CLOSE CURSOR_FUNCIONARIOS
    DEALLOCATE CURSOR_FUNCIONARIOS
END

--COMO TESTAR
--PRIMEIRO, FAZER ALGUMAS INSERÇÕES PARA TER DADOS NA TB_FUNCIONARIO
INSERT INTO TB_FUNCIONARIO (MATRICULA, NM_FUNCIONARIO, ANO_ADMISSAO, SALARIO)
VALUES 
(1, 'João Silva', 2005, 3000),
(2, 'Maria Oliveira', 2012, 4000),
(3, 'Pedro Santos', 2018, 2500),
(4, 'Ana Souza', 2009, 3500)

EXEC SP_ATUALIZA_SALARIO_FUNCIONARIOS

SELECT * FROM TB_FUNCIONARIO